pyinsta/pyinsta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('website/', include('website.urls')),
    path('admin/', admin.site.urls),
]

pyinsta/website/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'website'
urlpatterns = [
    # ex: /website/
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pyinsta/website/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
	name = models.CharField(max_length = 100)
	user_name = models.CharField(max_length = 20)
	birth_date = models.DateTimeField()
	def __str__(self):
		return self.user_name

class Account(models.Model):
	person = models.ForeignKey(Person, on_delete=models.CASCADE)
	profile = models.ImageField(upload_to ='img/profiles/%Y/%m/%d/', default='img/cage.jpg')

	def __str__(self):
		return str(self.person)

class Blog(models.Model):
	account = models.ForeignKey(Account, on_delete=models.CASCADE)

	def __str__(self):
		return str(self.account)

class Post(models.Model):
	blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
	pub_date = models.DateTimeField('date published')
	image = models.ImageField(upload_to ='img/posts/%Y/%m/%d/', default='img/cage.jpg')
	text = models.CharField(max_length = 200, default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec iaculis mauris.')
	def __str__(self):
		return str(self.blog)

pyinsta/website/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render

from .models import *

# Create your views here.
def index(request):
    latest_post_list = Post.objects.order_by('-pub_date')[:5]
    context = {'latest_post_list': latest_post_list}
    return render(request, 'website/index.html', context)

def detail(request, post_id):
    post = Post.objects.order_by('-pub_date')[:5]
    context = {'post': post}
    return render(request, 'website/index.html', context)

pyinsta/website/templates/website/index.html
<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Pyinsta</title>
    <link rel="stylesheet" href="/website/media/css/bulma.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  </head>
  <body>
    <!-- BARRA DE NAVEGACAO -->
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="https://bulma.io">
            <img src="/website/media/img/029-instagram.png" width="28" height="28">
          </a>
      
          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
      
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item">
                My Blog
            </a>
      
            <a class="navbar-item">
                Explore
            </a>

            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                Settings
              </a>
      
              <div class="navbar-dropdown">
                <a class="navbar-item">
                  About
                </a>
                <a class="navbar-item">
                  Change password
                </a>
                <a class="navbar-item">
                  Contact
                </a>
                <hr class="navbar-divider">
                <a class="navbar-item">
                  Report an issue
                </a>
              </div>
            </div>
          </div>

        </div>
    </nav>
      
    <section class="section">

      <div class="columns is-mobile is-centered">
          <div class="column is-half">
            <br>
            {% if latest_post_list %}
            {% for post in latest_post_list %}
            <div class="card">
              <div class="card-image">
                <figure class="image is-4by3">
                  <img src="/website{{post.blog.account.profile.url}}"alt="Placeholder image">
                </figure>
              </div>
              <div class="card-content">
                <div class="media">
                  <div class="media-left">
                    <figure class="image is-48x48">
                      <img src="/website{{post.image.url}}" alt="Placeholder image">
                    </figure>
                  </div>
                  <div class="media-content">
                    <p class="title is-4">{{post.blog.account.person.name}}</p>
                    <p class="subtitle is-6">@{{post.blog.account.person.user_name}}</p>
                  </div>
                </div>
                <div class="content">
                  {{post.text}} <a>@{{post.blog.account.person.user_name}}</a>.
                  <a href="#">#css</a> <a href="#">#responsive</a>
                  <br>
                  {{post.pub_date}}
                </div>
              </div>
            </div>
            <br>
            {% endfor %}
            {% else %}
              <p>No posts.</p>
            {% endif %}

          </div>
      </div>

    </section>
  </body>
</html>

pyinsta/website/templates/website/index_bkp.html
{% if latest_post_list %}
    <ul>
    {% for post in latest_post_list %}
        <li>
            <a href="{% url 'website:detail' post.id %}">{{ post.text }}</a>
                <br>
            <img src="/website{{post.image.url}}">
            
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No posts.</p>
{% endif %}